### ISSUE TITLE
Attributes are unexpectedly altered

### ISSUE THREAD

**Issue by MIchaelMainer** [OneDrive/apidoctor#2]
When inserting doc comments into the production metadata using:
`publish-edmx --path 'D:\repos\docs\api-reference\v1.0' --source "D:\repos\MSGraph-SDK-Code-Generator\metadata\2018_09_14\v1.0_2018_09_14_source_clean.xml" --output finalmetadata --skip-generation`
We find that ApiDoctor is altering the attributes. Specifically, it appears to not serialize the Nullable attribute value. This is an issue as the default value is true so it alters how we generate client libraries.
Secondly, the Unicode=false attribute is applied to all string properties and that doesn't match the source either. 

The left side is after MDS has processed and added annotations. The right side is after ApiDoctor has processed and added annotations.
![image](https://user-images.githubusercontent.com/8527305/46238128-199e6600-c33e-11e8-8dcc-8296a43ac50f.png)
This is happening to the parameters in the actions as well.

ref: [pr](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/143)

We will need to fix this before we move to ApiDoctor.

**Comment by MIchaelMainer** [comment]
Aww, its the merge policy, https://github.com/OneDrive/apidoctor/blob/master/ApiDoctor.Validation/OData/Property.cs#L50

**Comment by daspek** [comment]
Actually let's drill into this since it sounds like you know the most about what it should be. I basically gave up on the Unicode and nullable attributes since they didn't seem to be accurate or follow any rhyme or reason. We are free to make any changes you want here -- I don't think anyone else uses them. How should it work?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by MIchaelMainer** [comment]
Thanks Daron. I'll open a PR with the fix.

**Comment by MIchaelMainer** [comment]
@daspek Can you add me as a contributor to this repo? I think I'll be in here often enough.
